Docs/use nbqa on notebooks
aai-institute/tianshou pull request #1041
Opened 2024-02-02 15:22 UTC by carlocagnetta

- [ ] I have added the correct label(s) to this Pull Request or linked the relevant issue(s)
- [ ] I have provided a description of the changes in this Pull Request
- [ ] I have added documentation for my changes
- [ ] If applicable, I have added tests to cover my changes.
- [ ] I have reformatted the code using `poe format` 
- [ ] I have checked style and types with `poe lint` and `poe type-check`
- [ ] (Optional) I ran tests locally with `poe test` 
(or a subset of them with `poe test-reduced`) ,and they pass
- [ ] (Optional) I have tested that documentation builds correctly with `poe doc-build`

2024-02-02 15:41 UTC, carlocagnetta commented
@MischaPanch I would like to add nbqa ruff check and nbqa mypy to the pre-commit-config

2024-02-06 13:51 UTC, MischaPanch commented
> @MischaPanch I would like to add nbqa ruff check and nbqa mypy to the pre-commit-config

Sure, go ahead :)

2024-02-06 13:55 UTC, MischaPanch commented on pyproject.toml
> +_ruff_check_nb = "nbqa ruff docs/02_notebooks"
This is problematic b/c it's used in `poe lint` which is not supposed to format anything. However, this command actually formats the notebooks (even without the `--fix`). I know that `nbqua "ruff --check ."` didn't work for a mysterious reason, but I wouldn't want to modify the logic of lint. 

If you don't find a fix for  `nbqua "ruff --check .", we could introduce a new poe command `nb-lint-format` and call in in CI additionally to `poe lint`. It's not nice, but better than changing `lint` semantics. Then pls open an issue in the nbqa repository describing the problem and add a block comment here that links to the issue

2024-02-06 13:57 UTC, MischaPanch requested changes
Only the minor change in pyproject.toml is needed. You can also add the nbqa stuff to pre-commit. Then this is ready for merging, thanks @carlocagnetta !

2024-02-07 16:27 UTC, MischaPanch approved these changes

2024-02-07 16:28 UTC, merged