Added support for new PettingZoo API
aai-institute/tianshou pull request #751
Opened 2022-09-26 18:16 UTC by Markus28

Maybe someone who really knows PZ should do a sanity check here. I simply changed `step` to be compatible with both the old and the new step API. Removal of seeding was seemingly already anticipated in the existing code.

2022-09-26 20:56 UTC, Trinkle23897 approved these changes, later dismissed

2022-09-27 14:03 UTC, WillDudley requested changes
Thanks for the PR. I contend your choice to change the syntax, but I'm open to being convinced.

2022-09-27 14:03 UTC, WillDudley commented on tianshou/env/pettingzoo_env.py
> +        observation, info = last_return[0], last_return[-1]
Why have you done this rather than `observation, _, _, _, info = self.env.last(self)`  ? This would keep the style of Tianshou, Gym and PZ.

2022-09-27 14:03 UTC, WillDudley commented on tianshou/env/pettingzoo_env.py
> +        observation = last_return[0]
Why have you done this rather than `observation, _, _, truncation, termination, info = self.env.last(self)`  ? This would keep the style of Tianshou, Gym and PZ.

2022-09-27 14:03 UTC, WillDudley commented on tianshou/env/pettingzoo_env.py
> +        return (obs, self.rewards, *last_return[2:])  # type: ignore
`(obs, self.rewards, truncation, termination, info)` may be clearer.

2022-09-27 15:16 UTC, Markus28 commented
Yes, I completely agree with your remarks. The code was more readable before, due to the explicit labeling of the return values. 

I chose to do it this way to keep backwards compatibility with older PZ versions (which use the old step API). 
However, I'd also be open to imposing pettingzoo>=1.21.0 and using your proposed syntax. Unfortunately, I would expect this to break some user code.

We have a similar dilemma for Gym, but I don't believe that we should impose gym>=0.26.0 since this would probably break a lot of user code and (afaik) envpool has caught up with the API changes.

2022-09-27 15:17 UTC, Markus28 commented on tianshou/env/pettingzoo_env.py
> +        observation, info = last_return[0], last_return[-1]
See my comment below

2022-09-27 18:51 UTC, WillDudley commented
@Markus28 

Very good points. Indeed, some users may wish to use a new Tianshou feature with an old PZ env. However, I believe we do have wrappers to convert old PZ envs to new PZ envs pretty easily.

But the question is will the rest of Tianshou's update preserve backwards compat? Are you saying it will?

If it will, fab, but perhaps there should be warnings making users aware that:
a) the env they are using is old and may be incompatible with future updates, features & algos
b) it's easy to update the env by adding one extra line

2022-09-27 20:08 UTC, Markus28 commented
@WillDudley my changes to tianshou should be backward compatible with respect to *Gym and PettingZoo* in the sense that you should be able to use old-style environments without any issues. However, it is not entirely compatible with respect to *existing user code* since my changes may (slightly) break existing code that directly interacts with the replay buffer. I would expect few users to actually do that, given the abstraction offered by collectors and the `BasePolicy`.

So for all intents and purposes, I think one can call the changes backward compatible.

I agree that deprecation warnings may be reasonable. What do you think @Trinkle23897 @pseudo-rnd-thoughts?

2022-09-30 21:04 UTC, WillDudley commented
Would personally vote for a depreciation warning encouraging users to upgrade their envs with a simple wrapper (for maintenance reasons), as well as code comments explaining that the unconventional code logic is due to backwards compatibility with PettingZoo<1.21.

@Markus28

2022-10-01 19:49 UTC, WillDudley commented
LGTM!

2022-10-02 15:40 UTC, Trinkle23897 approved these changes

2022-10-02 16:33 UTC, merged