Feature/dataclasses
aai-institute/tianshou pull request #996
Opened 2023-11-23 15:36 UTC by maxhuettenrauch

- [ ] I have added the correct label(s) to this Pull Request or linked the relevant issue(s)
- [ ] I have provided a description of the changes in this Pull Request
- [ ] I have added documentation for my changes
- [ ] If applicable, I have added tests to cover my changes.
- [ ] I have reformatted the code using `poe format` 
- [ ] I have checked style and types with `poe lint` and `poe type-check`
- [ ] (Optional) I ran tests locally with `poe test` 
(or a subset of them with `poe test-reduced`) ,and they pass
- [ ] (Optional) I have tested that documentation builds correctly with `poe doc-build`

2023-11-24 18:07 UTC, Trinkle23897 reviewed
Overall lgtm, thanks for making things better! Could you please update all docs (.rst) and README to apply this change as well?

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/data/collector.py
>              * ``n/st`` collected number of steps.
could you also change here?

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/data/stats.py
> +    def to_dict(self, exclude: set[str] = None, exclude_arrays=True, exclude_none=True):
could you use pprint.pformat to override `__repr__`?

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/data/stats.py
> +        """The minimum of the array."""
This is pretty nice! Small nit: remove the duplicated docstring since it has already represented above.

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/data/stats.py
> +class UpdateStats(BaseStats):
better to move to `trainer/base.py` since it's only been used in trainer?

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/data/stats.py
> +class CollectStats(BaseStats):
better to move to `collector.py`?

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/data/stats.py
> +class InfoStats(BaseStats):
`trainer.py`?

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/data/stats.py
> +class EpochStats(BaseStats):
also `trainer.py`?

2023-11-24 18:07 UTC, Trinkle23897 commented on tianshou/policy/imitation/base.py
> +    class LossStats(BaseStats):
I think it's better to move all the `LossStats` classes out of the Policy class to make it more explicit instead of a nested one.

2023-11-24 19:59 UTC, MischaPanch commented
Hey @Trinkle23897, thanks for the quick review! 

This is still in draft status, @maxhuettenrauch and I are doing some internal rounds and going to do some more improvements and simplifications. Once it's done and tests pass, we'll ping you for a second review if you don't mind :)

2023-11-24 20:10 UTC, Trinkle23897 commented
Of course, no problem! Take your time

2023-11-30 23:49 UTC, MischaPanch requested changes

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/collector.py
>              * ``n/st`` collected number of steps.
The docstrings have to be adjusted, no need to tell which keys are contained since this information is in the type

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/stats.py
> +def flatten_dict(dictionary: dict, parent_key='', separator='/',
Add a docstring pls

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/stats.py
> +            elif isinstance(v, np.ndarray | list):
This seems a bit fishy

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/stats.py
> +    _array: np.ndarray | list[float] = field(repr=False)
This should be adjusted

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/collector.py
> +        :return: A dataclass object including the following keys
No need to write this, the type is self-documenting

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/collector.py
> +            rews_stat=SequenceSummaryStats.from_sequence(rews) if episode_count > 0 else None,
is the if-else here really necessary?

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/collector.py
> +        :return: A dataclass object including the following keys
See above

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/stats.py
> +@dataclass(kw_only=True)
remove annotation (there are no fields)

2023-11-30 23:49 UTC, MischaPanch commented on tianshou/data/stats.py
> +            assert hasattr(self, k), f"Unknown key {k} in stats dict {stats}."
turn to ValueError

2023-12-28 22:03 UTC, MischaPanch reviewed
From my side this is ready

2023-12-28 22:33 UTC, MischaPanch commented
@maxhuettenrauch I addressed several TODOs and made mypy happy. Thank you for all the work on this!

@Trinkle23897 @opcode81 @nuance1979 I have updated the PR description and highlighted the design decisions and reasons for them. It's ready to review

I wish everyone a happy rollout into New-Year! :)

2023-12-28 22:42 UTC, MischaPanch approved these changes

2023-12-30 00:46 UTC, Trinkle23897 commented on tianshou/policy/imitation/cql.py
> +        return CQLTrainingStats(  # type: ignore[return-value]
could you explain why do we need `type: ignore` for all TrainingStats?

2023-12-30 00:50 UTC, Trinkle23897 approved these changes

2023-12-30 10:09 UTC, merged